global:
  resolve_timeout: 30s

route:
  receiver: "self-healing-webhook"

  group_by:
    - alertname

  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h

receivers:

  - name: "self-healing-webhook"

    webhook_configs:

      - url: "http://webhook:5001/webhook"

        send_resolved: true
